theme = "molokai"

[editor]
color-modes = true
cursorcolumn = true
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["spinner", "mode", "version-control", "file-name", "file-modification-indicator"]
right = ["file-encoding", "file-line-ending", "file-type", "diagnostics", "selections", "position", "position-percentage"]

[editor.whitespace.render]
nbsp= "all"
newline = "all"
space = "none"
tab = "all"
tabpad = "."

[keys.normal."\\"]
q = ":bc"                                     # close buffer
Q = ":bca"                                    # close all buffers
w = ":toggle-option soft-wrap.enable"         # toggle line wrapping

[keys.normal."\\".c]
b = ":open ~/.bashrc"                         # open .bashrc file
l = ":open ~/.config/helix/languages.toml"    # open helix language configuration file
o = ":config-open"                            # open helix configuration file
p = ":open ~/.bash_profile"                   # open .bash_profile file
r = ":config-reload"                          # refresh helix configuration
s = ":open ~/.config/sway/config"             # open sway configuration file

[keys.normal."\\".n]
i = ":open ~/Git/sroemer/note-taking/index.md"
