theme = "molokai"

[editor]
color-modes = true
cursorcolumn = true
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.search]
smart-case = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["spinner", "mode", "version-control", "file-name", "file-modification-indicator"]
right = ["file-encoding", "file-line-ending", "file-type", "diagnostics", "selections", "position", "position-percentage"]

[editor.whitespace.render]
nbsp= "all"
newline = "all"
space = "none"
tab = "all"
tabpad = "."

[keys.normal]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection",  "make_search_word_bounded", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "make_search_word_bounded", "search_prev"]
X = "extend_line_above"                       # select current line or extend selection with line above it

[keys.normal."\\"]
q = ":bc"                                     # close buffer
Q = ":bca"                                    # close all buffers
w = ":toggle-option soft-wrap.enable"         # toggle line wrapping

[keys.normal."\\".c]
b = ":open ~/.bashrc"                         # open .bashrc file
l = ":open ~/.config/helix/languages.toml"    # open helix language configuration file
o = ":config-open"                            # open helix configuration file
p = ":open ~/.bash_profile"                   # open .bash_profile file
r = ":config-reload"                          # refresh helix configuration
s = ":open ~/.config/sway/config"             # open sway configuration file

[keys.normal."\\".n]
b = ":open ~/Git/sroemer/note-taking/cheat-sheets/linux/bash.md"        # open bash cheat sheet
d = ":open ~/Git/sroemer/note-taking/cheat-sheets/linux/development.md" # open development cheat sheet
h = ":open ~/Git/sroemer/note-taking/cheat-sheets/linux/helix.md"       # open helix editor cheat sheet
i = ":open ~/Git/sroemer/note-taking/index.md"                          # open index file of notes
